number1 = input ("Enter number1")
number1_two = input("Enter another number1")
print("Printing type of input value")
print ("type of number1 ", type(number1))
print ("type of number1_two ", type(number1_two ))
